export const languages = [
    {
        name: "Python",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/python.svg",
        logo_i: "devicon-python-plain",
        page: "",
        desc: "Learn fast. Tools built-in.",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(129,87%,9%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "JavaScript",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/javascript.svg",
        logo_i: "devicon-javascript-plain",
        desc: "Build powerful websites & more",
        i_color: "hsl(262,100%,100%)",
        background: "hsl(225,100%,14%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "Kotlin",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/kotlin.svg",
        logo_i: "devicon-kotlin-plain",
        desc: "Build powerful apps with JVM",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(0,0%,14%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "Java",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/java.svg",
        logo_i: "devicon-java-plain",
        page: "",
        desc: "Build powerful apps with JVM",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(0,0%,10%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "C#",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/csharp.svg",
        logo_i: "devicon-csharp-plain",
        desc: "Enjoy powerful capabilities from .NET",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(245,100%,15%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "C++",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/cplusplus.svg",
        logo_i: "devicon-cplusplus-plain",
        page: "",
        desc: "Build powerful apps.",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(239,100%,14%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "HTML",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/html.svg",
        logo_i: "devicon-html5-plain",
        page: "",
        desc: "Layout web pages & more.",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(216,100%,13%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "CSS",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/css.svg",
        logo_i: "devicon-css3-plain",
        page: "",
        desc: "Style web pages.",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(343,100%,10%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "Rust",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/rust.svg",
        logo_i: "devicon-rust-plain",
        page: "",
        desc: "Build powerful apps. ",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(31,100%,7%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "SQL<div style='font-size: 0.7rem'> (Postgres)</div>",
        icon: "/images/marbles/hi/d.png",
        logo: "/images/lang/postgresql.svg",
        logo_i: "devicon-postgresql-plain",
        page: "",
        desc: "Work powerfully with data.",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(212,100%,9%)",
        title_color: "hsl(0,0%,100%)"
    },
    {
        name: "PHP",
        icon: "/images/marbles/hi/d.png",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg",
        logo_i: "devicon-php-plain",
        page: "",
        desc: "Servers simplified",
        i_color: "hsl(0,0%,100%)",
        background: "hsl(181,100%,10%)",
        title_color: "hsl(0,0%,100%)"
    }
]

const symbols = [
    "\"",
    "#",
    "$",
    "%",
    "&",
    "",
    "(",
    ")",
    "*",
    "+",
    ",",
    "-",
    ".",
    "/",
    "!",
    ";",
    "<",
    "=",
    ">",
    "?",
    ":",
    "@",
    "\\",
    "]",
    "^",
    "_",
    "`",
    "[",
    "|",
    "}",
    "~",
    "{",
]